# -*- coding: utf-8 -*-

_author_ = 'luwt'
_date_ = '2023/7/13 10:37'


TOTAL_COUNT_LABEL_TEXT = '共 {} 条'
PAGE_SIZE_LABEL_TEXT = '条/页'
JUMP_PAGE_LEFT_LABEL_TEXT = '前往'
JUMP_PAGE_RIGHT_LABEL_TEXT = '页'

PAGE_SIZE_RANGE = ['5', '10', '20', '30', '50', '100']
FIRST_PAGE_BUTTON_TEXT = '首页'
PREVIOUS_PAGE_BUTTON_TEXT = '<'
NEXT_PAGE_BUTTON_TEXT = '>'
LAST_PAGE_BUTTON_TEXT = '尾页'
MORE_PAGE_BUTTON_TEXT = '···'
MORE_PAGE_RIGHT_BUTTON_TEXT = '>>'
MORE_PAGE_LEFT_BUTTON_TEXT = '<<'
