# -*- coding: utf-8 -*-

_author_ = 'luwt'
_date_ = '2023/7/26 9:39'


ADD_TASK_TITLE = '新建任务'
ADD_TASK_BOX_TITLE = '新建任务'
EDIT_TASK_TITLE = '编辑任务'
EDIT_TASK_BOX_TITLE = '编辑任务'
TASK_DETAIL_BOX_TITLE = '获取任务详情'

# 删除任务消息对话框标题
DEL_TASK_BOX_TITLE = '删除任务'
DEL_TASK_PROMPT = '任务：{}\n确认删除任务吗？'
BATCH_DEL_TASK_PROMPT = '已选择{}个任务\n确认删除选中的任务吗？'

BASIC_INFO_TEXT = '基本信息'
FEATURE_INFO_TEXT = '特征信息'
ATTACHMENT_INFO_TEXT = '附件信息'
PUBLISH_INFO_TEXT = '发版信息'

PROJECT_NAME_LABEL_TEXT = '项目名称：'
PROJECT_NAME_PLACEHOLDER_TEXT = '请选择项目名称'

TASK_NAME_LABEL_TEXT = '任务名称：'
TASK_NAME_PLACEHOLDER_TEXT = '请输入任务名称'

TASK_TYPE_LABEL_TEXT = '任务类型：'
TASK_TYPE_PLACEHOLDER_TEXT = '请选择任务类型'

DEMAND_PERSON_LABEL_TEXT = '需求方：   '
DEMAND_PERSON_PLACEHOLDER_TEXT = '请选择需求方'

PRIORITY_LABEL_TEXT = '优先级：'
PRIORITY_PLACEHOLDER_TEXT = '请选择优先级'

TASK_STATUS_LABEL_TEXT = '任务状态：'
TASK_STATUS_PLACEHOLDER_TEXT = '请选择任务状态'

PUBLISH_STATUS_LABEL_TEXT = '发版状态：'
PUBLISH_STATUS_PLACEHOLDER_TEXT = '请选择发版状态'

START_TIME_LABEL_TEXT = '开始时间：'
START_TIME_PLACEHOLDER_TEXT = '请选择开始时间'

END_TIME_LABEL_TEXT = '结束时间：'
END_TIME_PLACEHOLDER_TEXT = '请选择结束时间'

TIME_DURATION_LABEL_TEXT = '耗时：'
DETAIL_DESC_LABEL_TEXT = '任务详情：'

# 附件部分
ADD_ATTACHMENT_BUTTON_TEXT = '添加附件'
DOWNLOAD_ATTACHMENT_BUTTON_TEXT = '下载附件'
DELETE_ATTACHMENT_BUTTON_TEXT = '删除附件'

SELECT_ATTACHMENT_DIALOG_TITLE = '选择附件'
LOAD_ATTACHMENT_BOX_TITLE = '加载附件'
DOWNLOAD_ATTACHMENT_BOX_TITLE = '下载附件'

# 发版信息
ADD_PUBLISH_INFO_BUTTON_TEXT = '添加发版信息'
DELETE_PUBLISH_INFO_BUTTON_TEXT = '删除发版信息'
