# -*- coding: utf-8 -*-

_author_ = 'luwt'
_date_ = '2023/7/10 12:11'


WINDOW_TITLE = '工作任务管理器'

SWITCH_ADVANCED_SEARCH_BTN_TEXT = '高级查询'
SWITCH_BASIC_SEARCH_BTN_TEXT = '基本查询'
RESET_SEARCH_BTN_TEXT = '重置'
SEARCH_BTN_TEXT = '查询'
DEL_BTN_TEXT = '删除'

TASK_BOX_TITLE = '读取任务列表'

PROJECT_NAME_LABEL_TEXT = '项目名称：'
PROJECT_NAME_PLACEHOLDER_TEXT = '请选择项目名称'

TASK_NAME_LABEL_TEXT = '任务名称：'
TASK_NAME_PLACEHOLDER_TEXT = '请输入任务名称'

TASK_TYPE_LABEL_TEXT = '任务类型：'
TASK_TYPE_PLACEHOLDER_TEXT = '请选择任务类型'

DEMAND_PERSON_LABEL_TEXT = '需求方：'
DEMAND_PERSON_PLACEHOLDER_TEXT = '请选择需求方'

PRIORITY_LABEL_TEXT = '优先级：'
PRIORITY_PLACEHOLDER_TEXT = '请选择优先级'

TASK_STATUS_LABEL_TEXT = '任务状态：'
TASK_STATUS_PLACEHOLDER_TEXT = '请选择任务状态'

PUBLISH_STATUS_LABEL_TEXT = '发版状态：'
PUBLISH_STATUS_PLACEHOLDER_TEXT = '请选择发版状态'

START_TIME_LABEL_TEXT = '开始时间：'
START_TIME_PLACEHOLDER_TEXT = '请选择开始时间'

END_TIME_LABEL_TEXT = '结束时间：'
END_TIME_PLACEHOLDER_TEXT = '请选择结束时间'
